remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Indian Hills Community College Cloud DevOps Help Docs
description: All things DevOps to prepare minds to work as a DevOps Engineer, or DevOps minded developer. Used for the Cloud DevOps course and Indian Hills Community College
